name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Set up latest Oracle JDK 22'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 19
          version: 19.0.1

      - name: Run Maven tests
        run: mvn test -Punit-tests -DargLine="--add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-exports=java.management/com.sun.jmx.remote.security=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED"

  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: 'Set up latest Oracle JDK 22'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 19
          version: 19.0.1


      - name: Run Maven tests
        run: mvn test -Pintegration-tests -DargLine="--add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-exports=java.management/com.sun.jmx.remote.security=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED"
