name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Set JVM OPTIONS
        run: export JAVA_TOOL_OPTIONS='--add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED  --add-exports=java.management/com.sun.jmx.remote.security=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-opens=jdk.compiler/ com.sun.tools.javac.main=ALL-UNNAMED'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Maven tests
        run: mvn verify
