name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Run Maven tests
        run: mvn test -Punit-tests

  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Run Maven tests
        run: mvn test -Pintegration-tests
