name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Set up latest Oracle JDK 22'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 19
          version: 19.0.1

      - name: Run Maven tests
        run: mvn test -Punit-tests

  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: 'Set up latest Oracle JDK 22'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 19
          version: 19.0.1


      - name: Run Maven tests
        run: mvn test -Pintegration-tests
