name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: 'Set up archived Oracle JDK 17.0.10'
        uses: oracle-actions/setup-java@v1
        with:
            website: oracle.com
            release: 19
            version: 19.0.1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show File Structure
        run: ls -lrt

      - name: Run Maven tests
        run: mvn verify
